server:
  port: 8013
  servlet:
    context-path: /
spring:
  application:
    name: hq-multi-customer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8001/eureka/,http://root:123456@localhost:8002/eureka/
  instance:
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 2
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
    #状态页面和健康指标
    statusPageUrlPath: //swagger-ui.html
## Feign 开启 Hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 3000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
