server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8002/eureka/
  instance:
    hostname:hq-multi-eureka1
spring:
  security:
    user:
      name: root
      password: 123456
  application:
    name: hq-multi-eureka1
