server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8001/eureka/
      # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 10
  instance:
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 2
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
    #状态页面和健康指标
    statusPageUrlPath: //swagger-ui.html
spring:
  application:
    name: hq-multi-gateway
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    # 代理普通http请求的超时时间
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    ## http连接池大小
    max-total-connections: 300
    # 每个host最大连接数
    max-per-route-connections: 20
  ###前缀
  #prefix: /multi
  ##允许被忽略的服务
  #ignored-services: test-demo
  #网关限流
  ribbon-isolation-strategy: semaphore
  ##信号量模式下的最大并发，优先级最高，hystrix不生效
  semaphore:
    max-semaphores: 10000
  routes:
    customer:
      path: /consumer/**
      serviceId: hq-multi-customer


